const locations = [
  "Berlin",
  "Hamburg",
  "München",
  "Köln",
  "Frankfurt am Main",
  "Stuttgart",
  "Düsseldorf",
  "Dortmund",
  "Essen",
  "Leipzig",
  "Bremen",
  "Dresden",
  "Hannover",
  "Nürnberg",
  "Duisburg",
  "Bochum",
  "Wuppertal",
  "Bielefeld",
  "Bonn",
  "Münster",
  "Karlsruhe",
  "Mannheim",
  "Augsburg",
  "Wiesbaden",
  "Gelsenkirchen",
  "Mönchengladbach",
  "Braunschweig",
  "Chemnitz",
  "Kiel",
  "Aachen",
  "Halle (Saale)",
  "Magdeburg",
  "Freiburg im Breisgau",
  "Krefeld",
  "Lübeck",
  "Oberhausen",
  "Erfurt",
  "Mainz",
  "Rostock",
  "Kassel",
  "Hagen",
  "Saarbrücken",
  "Hamm",
  "Mülheim an der Ruhr",
  "Ludwigshafen am Rhein",
  "Potsdam",
  "Leverkusen",
  "Oldenburg",
  "Osnabrück",
  "Solingen",
  "Heidelberg",
  "Herne",
  "Neuss",
  "Darmstadt",
  "Paderborn",
  "Regensburg",
  "Ingolstadt",
  "Würzburg",
  "Fürth",
  "Ulm",
  "Heilbronn",
  "Pforzheim",
  "Göttingen",
  "Bottrop",
  "Reutlingen",
  "Koblenz",
];

export default locations;
