const locations = [
  "Ahmedabad, India",
  "Bangalore, India",
  "Beijing, China",
  "Bogotá, Colombia",
  "Buenos Aires, Argentina",
  "Cairo, Egypt",
  "Chengdu, China",
  "Chennai, India",
  "Chicago, United States",
  "Chongqing, China",
  "Delhi, India",
  "Dhaka, Bangladesh",
  "Guangzhou, China",
  "Hangzhou, China",
  "Ho Chi Minh City, Vietnam",
  "Hong Kong, China",
  "Hyderabad, India",
  "Istanbul, Turkey",
  "Jakarta, Indonesia",
  "Karachi, Pakistan",
  "Kinshasa, Democratic Republic of the Congo",
  "Kolkata, India",
  "Kuala Lumpur, Malaysia",
  "Lagos, Nigeria",
  "Lahore, Pakistan",
  "Lima, Peru",
  "London, United Kingdom",
  "Los Angeles, United States",
  "Luanda, Angola",
  "Manila, Philippines",
  "Mexico City, Mexico",
  "Moscow, Russia",
  "Mumbai, India",
  "Nagoya, Japan",
  "Nanjing, China",
  "New York City, United States",
  "Osaka, Japan",
  "Paris, France",
  "Rio de Janeiro, Brazil",
  "Seoul, South Korea",
  "Shanghai, China",
  "Shenzhen, China",
  "São Paulo, Brazil",
  "Tehran, Iran",
  "Tianjin, China",
  "Tokyo, Japan",
  "Wuhan, China",
];

export default locations;
